# Generated by Django 2.1 on 2020-06-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessTokens",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=60, unique=True)),
                ("token", models.CharField(max_length=24, unique=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
