# Generated by Django 2.2.13 on 2020-11-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security_manager", "0002_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password_hash",
            field=models.BinaryField(),
        ),
    ]
