# Generated by Django 2.2.13 on 2021-01-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security_manager", "0005_user_mac_address_unhashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstokens",
            name="token",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
