# Generated by Django 2.2.13 on 2021-01-10 00:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ap_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="session_id",
            field=models.CharField(
                default=uuid.uuid4, max_length=255, primary_key=True, serialize=False
            ),
        ),
    ]
