# Generated by Django 2.2.13 on 2021-01-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ap_manager", "0002_auto_20210110_0041"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
    ]
