# Generated by Django 2.2.13 on 2021-01-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ap_manager", "0003_auto_20210110_1652"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="display_filters",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ap_manager.Filters",
            ),
        ),
    ]
