# Generated by Django 2.2.13 on 2021-01-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap_manager', '0004_auto_20210110_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(default='Not available', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='model_number',
            field=models.CharField(default='Not available', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='os_version',
            field=models.CharField(default='Not available', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='user_agent',
            field=models.CharField(default='Not available', max_length=255),
        ),
    ]
