"""Constants used by the entire project."""

NOT_AVAILABLE = "Not available"

DEVICE_INFO = "Device_Info"
MAC_ADDRESS = "MAC Address"
MANUFACTURER = "Manufacturer"
MODEL_NUMBER = "Model Number"
USER_AGENT = "User-Agent"
OS_VERSION = "OS Version"
USER_PIN = "User_Pin"
DNS_QUERIES = "DNS_Queries"
INTERNET_TRAFFIC = "Internet_Traffic"
FILTERS = "Filters"
LAST_UPDATED = "Last_Updated"
SENSITIVE = "SENSITIVE"
NOT_SENSITIVE = "NOT SENSITIVE"
HTTP = "HTTP"
HTTPS = "HTTPS"
RATING = "rating"

DEVICE_ID = "device_id"
DEVICE_PIN = "device_pin"
SHOW_DEVICE_INFO = "show_device_info"
SHOW_DNS_QUERIES = "show_dns_queries"
SHOW_SECURE_INTERNET_TRAFFIC = "show_secure_internet_traffic"
SHOW_UNSECURE_INTERNET_TRAFFIC = "show_unsecure_internet_traffic"
DIFFERENTIATE_TRACKERS = "differentiate_trackers"
SHOW_DEVICE = "show_device"
DEVICE_POSITION = "device_position"

SESSION_ID = "session_id"
